implement useQuery custom react hook
AndcultureCode/AndcultureCode.JavaScript.React pull request #42
Opened 2020-10-05 14:16 UTC by mrjones2014

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [ ] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
Fixes #40

2020-10-09 13:33 UTC, wintondeshong requested changes
@mrjones2014 thanks for another contribution! 👏 - if you wouldn't mind the version upgrade as well as rename of service, then I'm good 👍

2020-10-09 13:33 UTC, wintondeshong commented on src/interfaces/use-query-options.ts
> +    service:
Nitpick: Alphabetize and per commentary above, rename to better convey that it is a 'hook' by way of its name

2020-10-09 15:34 UTC, mrjones2014 commented on src/hooks/use-query.ts
> +    const handleSuccess = useCallback(
They're using handlers passed in via options, that's why they need to be inside the hook.

2020-10-09 15:35 UTC, mrjones2014 commented
@wintondeshong comments should be addressed.

2020-10-11 15:37 UTC, wintondeshong approved these changes
Thanks for making those changes @mrjones2014

2020-10-28 12:08 UTC, brandongregoryscott approved these changes

2020-10-28 12:09 UTC, merged

2021-05-12 12:10 UTC, brandongregoryscott commented
@all-contributors add @mrjones2014 for code